

package com.seventythousand.wasteland.ruin;

import com.seventythousand.wasteland.items.LootStack;
import cpw.mods.fml.common.IWorldGenerator;
import com.seventythousand.wasteland.ModHelper;

import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

public class RuinSpawner extends Ruin implements IWorldGenerator {
  private RuinGenHelper genHelper = new RuinGenHelper();

  public RuinSpawner(String name) {
    super(name);
  }

  protected boolean generate(World world, Random random, int xCoord, int yCoord, int zCoord) {
    if (world.getHeightValue(xCoord + 4, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 4, zCoord - 1) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 0) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 1) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 2) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 3) == yCoord && world.getHeightValue(xCoord + 4, zCoord + 4) == yCoord && world.getHeightValue(xCoord + 3, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 3, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 2, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 2, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 1, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 1, zCoord + 5) == yCoord && world.getHeightValue(xCoord + 0, zCoord - 2) == yCoord && world.getHeightValue(xCoord + 0, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 1, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 1, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 2, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 2, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 3, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 3, zCoord + 5) == yCoord && world.getHeightValue(xCoord - 4, zCoord - 2) == yCoord && world.getHeightValue(xCoord - 4, zCoord + 5) == yCoord) {
      System.out.println("Generating Succesfully at: " + ModHelper.getCoordAsString(xCoord, yCoord, zCoord));
      RuinGenHelper.setWorld(world);
      yCoord--;
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, (Block)Blocks.chest);
      TileEntityChest chest = (TileEntityChest)world.getTileEntity(xCoord + 4, yCoord, zCoord + 4);
      LootStack loot = setItems(random);
      LootStack.placeLoot(random, chest, LootStack.getLootItems(random, loot.items, loot.minNum, loot.maxNum, loot.repeat));
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.planks);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.planks);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stone_stairs);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.planks);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.planks);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.air);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.planks);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.netherrack);
      RuinGenHelper.setBlock(xCoord - 2, yCoord + 1, zCoord + 4, (Block)Blocks.fire);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 1, Blocks.planks);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.planks);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 0, Blocks.planks);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.cobblestone);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, world.getHeightValue(xCoord + 3, zCoord - 4), zCoord - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, world.getHeightValue(xCoord - 2, zCoord - 4), zCoord - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, world.getHeightValue(xCoord - 5, zCoord - 5), zCoord - 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stone_stairs);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.torch);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 5, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 5, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 5, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 4, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 3, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 2, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 1, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(xCoord + 0, yCoord, zCoord + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 1, yCoord, zCoord + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 2, yCoord, zCoord + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(xCoord - 3, yCoord, zCoord + 2, Blocks.stonebrick, 2);
      return true;
    }
    return false;
  }

  private static ItemStack getLootItem(Random rand, ItemStack[] items) {
    int i = rand.nextInt(items.length);
    ItemStack itemStack = new ItemStack(items[i].getItem(), 1);
    if (itemStack.getItem() == Items.rotten_flesh)
      return new ItemStack(itemStack.getItem(), rand.nextInt(4) + 2);
    if (itemStack.getItem() == Items.bucket)
      return new ItemStack(itemStack.getItem(), rand.nextInt(3) + 1);
    if (itemStack.getItem() == Items.spider_eye)
      return new ItemStack(itemStack.getItem(), rand.nextInt(5) + 1);
    if (itemStack.getItem() == Items.record_chirp)
      return new ItemStack(itemStack.getItem(), 1);
    if (itemStack.getItem() == Items.name_tag)
      return new ItemStack(itemStack.getItem(), rand.nextInt(1) + 1);
    if (itemStack.getItem() == Items.potato)
      return new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1);
    if (itemStack.getItem() == Items.carrot)
      return new ItemStack(itemStack.getItem(), rand.nextInt(2) + 1);
    if (itemStack.getItem() == Items.feather)
      return new ItemStack(itemStack.getItem(), rand.nextInt(9) + 4);
    if (itemStack.getItem() == Items.leather_chestplate)
      return new ItemStack(itemStack.getItem(), 1, itemStack.getMaxDamage() - rand.nextInt(itemStack.getMaxDamage() / 2));
    return itemStack;
  }
}
