

package com.seventythousand.wasteland.ruin;

import com.hbm.blocks.ModBlocks;
import com.hbm.tileentity.machine.storage.TileEntityCrateBase;
import com.seventythousand.wasteland.config.CityLootConfig;
import com.seventythousand.wasteland.config.ModConfig;
import com.seventythousand.wasteland.config.RuinConfig;
import com.seventythousand.wasteland.items.LootStack;
import com.seventythousand.wasteland.utils.Rectangle;
import com.seventythousand.wasteland.utils.Vector;
import cpw.mods.fml.common.IWorldGenerator;

import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

public class RuinRuined extends Ruin implements IWorldGenerator {
  private RuinGenHelper genHelper = new RuinGenHelper();

  public RuinRuined(String par1Name) {
    super(par1Name);
  }

  public boolean generate(World world, Random rand, int x, int y, int z) {
    RuinGenHelper.setWorld(world);
    Rectangle pos = new Rectangle(new Vector(x - 5, y, z - 6), 10, 12);
    int[] lay = Layout.getLevels(world, pos);
    Block surfaceBlock = ModConfig.getSurfaceBlock();
    if (Layout.checkLevel(lay, 3)) {
        int yCoord = Layout.getMinLevel(lay);
        RuinGenHelper.setBlock(x + 4, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 6, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 3, surfaceBlock);

      RuinGenHelper.setBlock(x + 2, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 7, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord +  1, z + 3, ModBlocks.mine_he);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 7, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.netherrack);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 6, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 6, yCoord, z - 6, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 7, yCoord, z - 4, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 7, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 5, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 5, yCoord, z + 7, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 1,ModBlocks.lightstone_tile_stairs);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 6, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone, 2);
      Building.handleLoot(world, rand, x - 2, yCoord, z + 4);

      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2,ModBlocks.lightstone_tile_stairs);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 3, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3,ModBlocks.lightstone_tile_stairs);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x + 2, yCoord + 1, z - 3, ModBlocks.mine_he, 1);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 2, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, x - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 0, ModBlocks.lightstone, 1);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 0, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, x + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.mine_ap);

      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, (Block) ModBlocks.safe);
      TileEntityCrateBase safe = (TileEntityCrateBase) world.getTileEntity(x - 4, yCoord, z - 2);
      safe.setMod(0.25);
      safe.setPins(rand.nextInt(999) + 1);
      safe.lock();
      LootStack.placeLoot(rand, safe, RuinConfig.getLoot(rand.nextBoolean() ? CityLootConfig.ultraLoot : RuinConfig.hardLoot), 27, 26);

      RuinGenHelper.setBlock(x - 2, yCoord, z - 2, ModBlocks.turret_sentry_damaged);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, ModBlocks.lightstone);
      yCoord++;
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, ModBlocks.lightstone);
      yCoord++;
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone, 2);
      yCoord++;
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, ModBlocks.lightstone);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, ModBlocks.lightstone);
      return true;
    }
    return false;
  }
}
