

package myid.chiqors.wasteland.ruin;

import cpw.mods.fml.common.IWorldGenerator;
import myid.chiqors.wasteland.config.ModConfig;
import myid.chiqors.wasteland.items.LootStack;
import myid.chiqors.wasteland.utils.CustomItemStack;
import myid.chiqors.wasteland.utils.Rectangle;
import myid.chiqors.wasteland.utils.Vector;
import java.util.Random;
import net.minecraft.block.Block;
import net.minecraft.init.Blocks;
import net.minecraft.tileentity.TileEntityChest;
import net.minecraft.world.World;

public class RuinRuined extends Ruin implements IWorldGenerator {
  private RuinGenHelper genHelper = new RuinGenHelper();
  
  public RuinRuined(String par1Name) {
    super(par1Name);
  }
  
  public boolean generate(World world, Random rand, int x, int y, int z) {
    RuinGenHelper.setWorld(world);
    Rectangle pos = new Rectangle(new Vector(x - 5, y, z - 6), 10, 12);
    int[] lay = Layout.getLevels(world, pos);
    Block surfaceBlock = ModConfig.getSurfaceBlock();
    if (Layout.checkLevel(lay, 3)) {
        int yCoord = Layout.getMinLevel(lay);
        RuinGenHelper.setBlock(x + 4, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 6, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 7, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 7, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.netherrack);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 1, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 6, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, surfaceBlock);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, surfaceBlock);
      RuinGenHelper.setBlock(x - 6, yCoord, z - 6, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 7, yCoord, z - 4, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 7, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 5, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 5, yCoord, z + 7, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 1, Blocks.stone_stairs);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 6, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, Blocks.cobblestone);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.cobblestone);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 4, (Block)Blocks.fire);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2, Blocks.stone_stairs);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.stone_stairs);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 3, Blocks.cobblestone);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 2, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, x - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 3, yCoord, z + 0, Blocks.cobblestone);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 2, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 1, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 0, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 3, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 1, Blocks.log);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, x + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 4, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 2, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x + 1, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x + 0, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 1, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 3, yCoord, z + 5, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 1, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 3, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x + 4, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 2, yCoord, z + 5, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 2, (Block)Blocks.chest);
      TileEntityChest chest = (TileEntityChest)world.getTileEntity(x - 4, yCoord, z - 2);
      LootStack loot = setItems(rand);
      CustomItemStack.placeLoot(rand, chest, CustomItemStack.getLootItems(rand, loot.items, loot.minNum, loot.maxNum, loot.repeat));
      RuinGenHelper.setBlock(x - 4, yCoord, z + 4, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z + 0, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(x - 3, yCoord, z - 4, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 1, Blocks.stonebrick);
      yCoord++;
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick, 2);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick, 2);
      yCoord++;
      RuinGenHelper.setBlock(x - 4, yCoord, z - 3, Blocks.stonebrick);
      RuinGenHelper.setBlock(x - 5, yCoord, z - 2, Blocks.stonebrick);
      return true;
    } 
    return false;
  }
}
